//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oto_Galeri
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArabaTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArabaTable()
        {
            this.IslemTable = new HashSet<IslemTable>();
        }
    
        public int A_ID { get; set; }
        public string A_No { get; set; }
        public string A_Marka { get; set; }
        public string A_Model { get; set; }
        public string A_Tip { get; set; }
        public string A_Renk { get; set; }
        public string A_Yakit { get; set; }
        public string A_Vites { get; set; }
        public string A_Yil { get; set; }
        public Nullable<int> A_Fiyat { get; set; }
        public string A_Tarih { get; set; }
        public string A_Plaka { get; set; }
        public Nullable<int> S_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IslemTable> IslemTable { get; set; }
        public virtual SubeTable SubeTable { get; set; }
    }
}
