//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oto_Galeri
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemTable
    {
        public int Is_ID { get; set; }
        public Nullable<int> Is_Fiyat { get; set; }
        public string Is_Tar { get; set; }
        public Nullable<int> M_ID { get; set; }
        public Nullable<int> A_ID { get; set; }
        public Nullable<int> T_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
    
        public virtual ArabaTable ArabaTable { get; set; }
        public virtual MusteriTable MusteriTable { get; set; }
        public virtual PersonelTable PersonelTable { get; set; }
        public virtual TipTable TipTable { get; set; }
    }
}
