//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oto_Galeri
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriTable()
        {
            this.IslemTable = new HashSet<IslemTable>();
            this.MSifreTable = new HashSet<MSifreTable>();
        }
    
        public int M_ID { get; set; }
        public string M_TC { get; set; }
        public string M_AD { get; set; }
        public string M_Soyad { get; set; }
        public string M_Tel { get; set; }
        public string M_Cins { get; set; }
        public string M_Dyil { get; set; }
        public string M_Mail { get; set; }
        public string M_Ehliyet { get; set; }
        public Nullable<int> I_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IslemTable> IslemTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSifreTable> MSifreTable { get; set; }
        public virtual IlTable IlTable { get; set; }
    }
}
